# Generated by Django 4.0.2 on 2024-10-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('D', 'Doctor'), ('P', 'Patient')], max_length=10),
        ),
    ]
